package smux

const (
	START_STREAM_ID_OF_CLIENT = 1
	START_STREAM_ID_OF_SERVER = 2

	NUM_BYTES_HEADER      = 8
	NUM_BYTES_MAX_PAYLOAD = 1 << 14 // 16384 bytes = 16kb

	TYPE_DATA = 0

	FLAG_DATA_NONE       = 0
	FLAG_DATA_END_STREAM = 1
)
